import VoyagerEntitiesEntry

public typealias EntrySupplementaryMetadata = VoyagerEntitiesEntry.EntrySupplementaryMetadata
public typealias EntryFacets = VoyagerEntitiesEntry.EntryFacets
public typealias EntryModel = VoyagerEntitiesEntry.EntryModel
