[project]
name = "voyager-app-backend"
version = "0.1.0"
description = "Voyager App Backend With FastAPI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "fastapi[standard]==0.116.1",
  "hydra-core>=1.3.2",
  "langchain-community>=0.3.0",
  "langchain-core>=0.3.0",
  "langchain-teddynote>=0.1.0",
  "langchain-unstructured>=0.1.0",
  "osxmetadata>=1.4.0",
  "pandas>=2.0.0",
  "pydantic>=2.11.7",
  "python-dotenv>=1.1.1",
  "uvicorn[standard]==0.35.0",
]

[dependency-groups]
dev = [
  "ipykernel>=6.30.1",
  "nbstripout>=0.8.1",
  "pandas-stubs>=2.3.2.250827",
  "pre-commit>=4.3.0",
  "pyright>=1.1.375",
  "ruff>=0.7.0",
  "uv>=0.8.13",
]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["FAST"]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false


[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"

[tool.uv]
package = true

[tool.uv.build-backend]
module-name = "app"

[project.scripts]
dev = "app.cli:dev"
prod = "app.cli:prod"

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = "none"
pythonVersion = "3.13"
reportUnnecessaryTypeIgnoreComment = "error"
reportUnnecessaryCast = "error"
reportUnreachable = "error"
exclude = [
  "**/.venv",
  "**/.venv/**",
  "**/site-packages/**",
]
ignore = [
  "**/.venv",
  "**/.venv/**",
  "**/site-packages/**",
]
