"""update file_entries

Revision ID: 08ad2d8a0bf4
Revises: 52b6d89590e3
Create Date: 2025-09-20 02:59:44.327377+00:00

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "08ad2d8a0bf4"
down_revision: Union[str, None] = "52b6d89590e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("original_stat", sa.JSON(), nullable=True))
        batch_op.drop_column("mode")
        batch_op.drop_column("where_from")
        batch_op.drop_column("finder_tags")
        batch_op.drop_column("nlink")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nlink", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("finder_tags", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("where_from", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("mode", sa.INTEGER(), nullable=False))
        batch_op.drop_column("original_stat")

    # ### end Alembic commands ###
