package propertycatalog

import (
	"fmt"
	"sort"
	"strings"
)

// renderConditionCatalog renders the generated property_condition_catalog_gen.go
// source that carries the compiled Condition Registry dataset (version, 20
// operators, all 42 (operator, native_type) relations plus value shape/count,
// inverse, UI value kind, and MDQuery hint).
func renderConditionCatalog(registry *PropertyConditionRegistry) (string, error) {
	operators := registry.OperatorsSorted()
	relations := registry.Relations()

	var builder strings.Builder
	builder.WriteString(`// Code generated by internal/tools/property-catalog. DO NOT EDIT.
//
// Compiled Property Condition Registry (v2.2.0). Executable condition semantics
// are owned by this generated Go catalog; no SQLite condition table exists.
package entry

// ConditionCatalogVersion is the compiled Property Condition Registry version.
const ConditionCatalogVersion = "` + registry.Version + `"

`)
	builder.WriteString("var conditionOperators = []ConditionOperator{\n")
	for _, operator := range operators {
		builder.WriteString("\t{ID: " + goString(operator.Name) + ",\n")
		builder.WriteString("\t\tUISource: " + goString(operator.Spec.UISource) + ",\n")
		builder.WriteString("\t\tValueShape: " + conditionValueShapeLiteral(operator.Spec.ValueShape) + ",\n")
		builder.WriteString("\t\tValueCount: " + fmt.Sprintf("%d", parseValueCount(operator.Spec.ValueCount)) + ",\n")
		builder.WriteString("\t\tInverseOf: " + goString(operator.Spec.InverseOf) + ",\n")
		builder.WriteString("\t\tMDQueryHint: " + goString(operator.Spec.MDQueryHint) + ",\n")
		builder.WriteString("\t\tUISourceByType: map[ConditionNativeType]ConditionUISourceKind{\n")
		// UISourceByType는 allowed_types에 존재하는 native type만 포함한다.
		// Registry ui_value_kind는 allowed_types 밖의 키(예: neq|boolean)를
		// 포함할 수 있는데, 이를 그대로 복사하면 relation에 없는 spurious
		// (operator, native_type) UI 관계가 생성되므로 allowed_types로 제한한다.
		allowed := make(map[string]struct{}, len(operator.Spec.AllowedTypes))
		for _, allowedType := range operator.Spec.AllowedTypes {
			allowed[allowedType] = struct{}{}
		}
		typeKeys := make([]string, 0, len(operator.Spec.UISourceByType))
		for nativeType := range operator.Spec.UISourceByType {
			if _, ok := allowed[nativeType]; ok {
				typeKeys = append(typeKeys, nativeType)
			}
		}
		sort.Strings(typeKeys)
		for _, nativeType := range typeKeys {
			builder.WriteString("\t\t\t" + conditionNativeTypeLiteral(nativeType) + ": " + goString(operator.Spec.UISourceByType[nativeType]) + ",\n")
		}
		builder.WriteString("\t\t},\n")
		builder.WriteString("\t},\n")
	}
	builder.WriteString("}\n\n")

	builder.WriteString("var conditionRelations = []ConditionRelation{\n")
	for _, relation := range relations {
		builder.WriteString("\t{Operator: " + goString(relation.Operator) + ", NativeType: " + conditionNativeTypeLiteral(string(relation.NativeType)) + ", UISourceKind: " + goString(string(relation.UISourceKind)) + "},\n")
	}
	builder.WriteString("}\n\n")

	builder.WriteString(`// ConditionCatalogData is the compiled immutable Condition Registry catalog.
var ConditionCatalogData = newConditionCatalog(ConditionCatalogVersion, conditionOperators, conditionRelations)
`)
	return builder.String(), nil
}

func conditionValueShapeLiteral(shape string) string {
	switch shape {
	case "single":
		return "ConditionValueShapeSingle"
	case "none":
		return "ConditionValueShapeNone"
	case "range":
		return "ConditionValueShapeRange"
	case "list":
		return "ConditionValueShapeList"
	default:
		return "ConditionValueShapeNone"
	}
}

func conditionNativeTypeLiteral(nativeType string) string {
	switch nativeType {
	case "string":
		return "ConditionNativeTypeString"
	case "number":
		return "ConditionNativeTypeNumber"
	case "date":
		return "ConditionNativeTypeDate"
	case "boolean":
		return "ConditionNativeTypeBoolean"
	case "string_list":
		return "ConditionNativeTypeStringList"
	case "categorical":
		return "ConditionNativeTypeCategorical"
	default:
		return "ConditionNativeTypeString"
	}
}

func goString(value string) string {
	return fmt.Sprintf("%q", value)
}

// renderCatalogGen renders the generated seeds/catalog_gen.go metadata record.
// The SQL body itself is embedded by the hand-authored embed.go; this file
// carries only the generated constants and hashes.
func renderCatalogGen(projection ProjectedCatalog, sqlBody string, registry *SystemPropertyRegistry) (string, error) {
	var builder strings.Builder
	builder.WriteString(`// Code generated by internal/tools/property-catalog. DO NOT EDIT.
//
// Generated metadata for the System Property Registry full-state SQL seed.
package seeds

// generatedSeedMetadata is the immutable generated metadata for the committed
// seed. Current() in catalog.go assembles it with the embedded SQL body.
var generatedSeedMetadata = SeedMetadata{
	SeedOrdinal:        ` + intLiteral(SeedVersion) + `,
	SystemRegistryVersion: "` + registry.Version + `",
	SQLSHA256:          "` + SQLSHA256(sqlBody) + `",
	DatasetSHA256:      "` + DatasetDigestHex(projection) + `",
	DefinitionCount:    ` + intLiteral(len(projection.Definitions)) + `,
	DescriptorCount:    ` + intLiteral(len(projection.Descriptors)) + `,
	BindingCount:       ` + intLiteral(len(projection.Bindings)) + `,
	TermCount:          ` + intLiteral(len(projection.Terms)) + `,
}
`)
	return builder.String(), nil
}

// validateConditionCounts verifies the 20-operator / 42-relation invariant of
// the compiled catalog against the raw registry.
func validateConditionCounts(registry *PropertyConditionRegistry) error {
	if len(registry.Operators) != 20 {
		return fmt.Errorf("expected 20 operators, got %d", len(registry.Operators))
	}
	relations := registry.Relations()
	if len(relations) != 42 {
		return fmt.Errorf("expected 42 (operator, allowed_type) relations, got %d", len(relations))
	}
	seen := make(map[string]struct{}, len(relations))
	for _, relation := range relations {
		key := relation.Operator + "\x00" + string(relation.NativeType)
		if _, exists := seen[key]; exists {
			return fmt.Errorf("duplicate relation %s/%s", relation.Operator, relation.NativeType)
		}
		seen[key] = struct{}{}
	}
	return nil
}
