defaults:
  - env: dev
  - db: sqlite
  - _self_

app:
  name: voyager

# LLM 설정 (LangChain 기반)
llm:
  provider: openai # ollama, openai, anthropic
  # model: gpt-5-nano-2025-08-07
  model: gpt-5-mini-2025-08-07
  temperature: 0.3 # SQL 생성은 낮은 temperature 권장

  # Provider별 설정
  ollama:
    base_url: http://localhost:11434

  openai:
    api_key: ${oc.env:OPENAI_API_KEY}

  anthropic:
    api_key: ${oc.env:ANTHROPIC_API_KEY,""}
