#!/usr/bin/env bash
set -euo pipefail

BUILD_DIR="${BUILD_DIR:-${PWD}/build/ci}"
PROJECT_PATH="${PROJECT_PATH:-}"
SCHEME="${SCHEME:-}"
CONFIGURATION="${CONFIGURATION:-Prod-Release}"
CURRENT_PROJECT_VERSION_OVERRIDE="${CURRENT_PROJECT_VERSION_OVERRIDE:-}"
VOYAGER_RELEASED_AT="${VOYAGER_RELEASED_AT:-}"
SWIFT_OPTIMIZATION_LEVEL_OVERRIDE="${SWIFT_OPTIMIZATION_LEVEL_OVERRIDE:-}"

if [[ -z "${SWIFT_OPTIMIZATION_LEVEL_OVERRIDE}" && "${CONFIGURATION}" == "Prod-Release" ]]; then
  SWIFT_OPTIMIZATION_LEVEL_OVERRIDE="-Osize"
fi

if [[ -z "${PROJECT_PATH}" || -z "${SCHEME}" ]]; then
  echo "Missing PROJECT_PATH or SCHEME." >&2
  exit 1
fi

mkdir -p "${BUILD_DIR}"

xcodebuild \
  -project "${PROJECT_PATH}" \
  -scheme "${SCHEME}" \
  -configuration "${CONFIGURATION}" \
  -archivePath "${BUILD_DIR}/Voyager.xcarchive" \
  -derivedDataPath "${BUILD_DIR}/DerivedData" \
  -clonedSourcePackagesDirPath "${BUILD_DIR}/SourcePackages" \
  ${CURRENT_PROJECT_VERSION_OVERRIDE:+CURRENT_PROJECT_VERSION=${CURRENT_PROJECT_VERSION_OVERRIDE}} \
  ${VOYAGER_RELEASED_AT:+VOYAGER_RELEASED_AT=${VOYAGER_RELEASED_AT}} \
  ${SWIFT_OPTIMIZATION_LEVEL_OVERRIDE:+SWIFT_OPTIMIZATION_LEVEL=${SWIFT_OPTIMIZATION_LEVEL_OVERRIDE}} \
  archive
