// Code generated by internal/tools/property-catalog. DO NOT EDIT.
//
// Generated metadata for the System Property Registry full-state SQL seed.
package seeds

// generatedSeedMetadata is the immutable generated metadata for the committed
// seed. Current() in catalog.go assembles it with the embedded SQL body.
var generatedSeedMetadata = SeedMetadata{
	SeedOrdinal:           1,
	SystemRegistryVersion: "2.4.1",
	SQLSHA256:             "4dfbbfb382038b1cd749ee9d7befbebead4b773617920cd586436c26f2444bff",
	DatasetSHA256:         "f11f29392a27c9ca99b9b2567e76fc8dd4e3d0825766124d0735fb1562d93a4b",
	DefinitionCount:       278,
	DescriptorCount:       294,
	BindingCount:          296,
	TermCount:             441,
}
