// Code generated by internal/tools/property-catalog. DO NOT EDIT.
//
// Generated metadata for the System Property Registry full-state SQL seed.
package seeds

// generatedSeedMetadata is the immutable generated metadata for the committed
// seed. Current() in catalog.go assembles it with the embedded SQL body.
var generatedSeedMetadata = SeedMetadata{
	SeedOrdinal:           1,
	SystemRegistryVersion: "2.4.1",
	SQLSHA256:             "53f7b586810f0005d1212ca3e42fed0b6c3f18fd00c9d07c3fbf9c8eb9d35a16",
	DatasetSHA256:         "f0fb5b638de4f84e854f187dfd08330fb44c6f85a7913189b78cdf1a7ca930fd",
	DefinitionCount:       278,
	DescriptorCount:       294,
	BindingCount:          296,
	TermCount:             441,
}
