import ComposableArchitecture
import Foundation
import VoyagerEntitiesEntry

public typealias RegistryClient = VoyagerEntitiesEntry.RegistryClient
public typealias PropertyKeyResolution = VoyagerEntitiesEntry.PropertyKeyResolution
