/**
 * entry-thumbnail-fixtures.ts
 *
 * Static import paths for generated entry thumbnail fixtures.
 * Generated by: scripts/generate-entry-thumbnail-fixtures.mjs
 *
 * Each key maps to a deterministic macOS QuickLook thumbnail
 * rendered from the fixture corpus under fixtures/fixtures/.
 * Multiple variations per kind provide visual diversity in grids/lists.
 */

export const entryThumbnailFixtures = {
  // PDF (5 variations)
  pdf: new URL("../assets/entry-thumbnails/pdf-sample.png", import.meta.url).href,
  pdfTest: new URL("../assets/entry-thumbnails/pdf-test.png", import.meta.url).href,
  pdf150k: new URL("../assets/entry-thumbnails/pdf-150k.png", import.meta.url).href,
  pdf1mb: new URL("../assets/entry-thumbnails/pdf-1mb.png", import.meta.url).href,
  pdf5mb: new URL("../assets/entry-thumbnails/pdf-5mb.png", import.meta.url).href,

  // Image (4 variations: PNG x2, JPEG, GIF)
  image: new URL("../assets/entry-thumbnails/image-hopper.png", import.meta.url).href,
  imageTransparent: new URL("../assets/entry-thumbnails/image-transparent.png", import.meta.url)
    .href,
  imageJpeg: new URL("../assets/entry-thumbnails/image-jpeg.png", import.meta.url).href,

  // GIF
  gif: new URL("../assets/entry-thumbnails/gif-hopper.png", import.meta.url).href,

  // Word (4 variations)
  word: new URL("../assets/entry-thumbnails/office-word.png", import.meta.url).href,
  wordTest: new URL("../assets/entry-thumbnails/office-word-test.png", import.meta.url).href,
  wordTabs: new URL("../assets/entry-thumbnails/office-word-tabs.png", import.meta.url).href,
  word59378: new URL("../assets/entry-thumbnails/office-word-59378.png", import.meta.url).href,

  // Spreadsheet (4 variations)
  workbook: new URL("../assets/entry-thumbnails/office-excel.png", import.meta.url).href,
  workbookBudget: new URL("../assets/entry-thumbnails/office-excel-budget.png", import.meta.url)
    .href,
  workbookCharts: new URL("../assets/entry-thumbnails/office-excel-charts.png", import.meta.url)
    .href,
  workbook46535: new URL("../assets/entry-thumbnails/office-excel-46535.png", import.meta.url).href,

  // Pages (2 variations)
  pages: new URL("../assets/entry-thumbnails/iwork-pages.png", import.meta.url).href,
  pagesVideo: new URL("../assets/entry-thumbnails/iwork-pages-video.png", import.meta.url).href,

  // Video (3 variations)
  video: new URL("../assets/entry-thumbnails/video-test-1s.png", import.meta.url).href,
  videoMovie: new URL("../assets/entry-thumbnails/video-movie5.png", import.meta.url).href,
  videoCounting: new URL("../assets/entry-thumbnails/video-counting.png", import.meta.url).href,

  // Text (4 variations)
  text: new URL("../assets/entry-thumbnails/text-sample.png", import.meta.url).href,
  textShort: new URL("../assets/entry-thumbnails/text-short.png", import.meta.url).href,
  text3296: new URL("../assets/entry-thumbnails/text-3296.png", import.meta.url).href,
  text1497: new URL("../assets/entry-thumbnails/text-1497.png", import.meta.url).href,

  // System icons (NSWorkspace)
  archive: new URL("../assets/entry-thumbnails/archive-system.png", import.meta.url).href,
  folder: new URL("../assets/entry-thumbnails/folder-system.png", import.meta.url).href,
} as const
