driver: sqlite
echo: ${app.debug}
check_same_thread: false

file_map:
  dev: voyager.dev.db
  prod: ~/Library/Application \Support/Voyager/voyager.db

file: ${oc.select:db.file_map.${app.env}, ${db.file_map.dev}}
protocol: ${db.driver}:///
