defaults:
  - env: dev
  - _self_

app:
  name: voyager
  env: ${env.name}

llm:
  provider: openai
  api_key: ${oc.env:OPENAI_API_KEY, ""}
  org_id: ${oc.env:OPENAI_ORG_ID, ""}
  project: ${oc.env:OPENAI_PROJECT, ""}

  chat_model: gpt-5-nano
  embedding_model: text-embedding-3-small
  timeout_s: 30

libreoffice:
  soffice_path: "../../resources/LibreOffice.app/Contents/MacOS/soffice"
